package com.liftuz.demovaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.util.List;

/**
 * Created by RawinNgamloet on 6/5/2017.
 */
@Component
public class TodoList extends VerticalLayout implements TodoChangedListener {
    @Autowired
    TodoRepository repository;

    @PostConstruct
    void init() {
        setSpacing(true);

        update();
    }

    private void update() {
        setTodos(repository.findAll());
    }

    public void setTodos(List<Todo> todos) {
        removeAllComponents();

        todos.forEach( t -> {
            addComponent(new TodoLayout(t, this));
        });
    }

    public void add(Todo todo) {
        repository.save(todo);
        update();
    }

    @Override
    public void todoChanged(Todo todo) {
        repository.save(todo);
    }
}
